x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:
  luxonis:
    image: husarion/depthai:humble-2.7.4-20230830
    <<: *net-config
    volumes:
      - ./config/camera.yaml:/ros2_ws/install/depthai_ros_driver/share/depthai_ros_driver/config/camera.yaml
    command: ros2 launch depthai_ros_driver camera.launch.py 

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    <<: *net-config
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-1to2-topics
  #   volumes:
  #     - ./config/bridge_topics.yaml:/bridge_topics.yaml
  #   command: bash -c "rosparam load /bridge_topics.yaml && ros2 run ros1_bridge parameter_bridge"

  foxglove:
    image: husarion/foxglove:humble-add-panther
    volumes:
      - ./config/foxglove.json:/src/FoxgloveDefaultLayout.json
      - ./config/panther_ouster.urdf:/src/panther.urdf
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090
    ports:
      - 8080:8080

# TODO add ros-humble-tf2-msgs
  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230831
    <<: *net-config
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml max_message_size:=50000000 use_compression:=true
  
  # TODO 
  ouster-lidar:
    image: husarion/ouster:humble-0.10.2-20230831
    <<: *net-config
    command: >
      ros2 launch ouster_ros sensor.composite.launch.xml
        timestamp_mode:=TIME_FROM_ROS_TIME
        metadata:=/ouster_metadata.json
        viz:=false
        sensor_hostname:=10.15.20.10
        lidar_mode:=512x10
        
# sensor_frame:=base_link

